#!/bin/sh
# Regenerate NOTICES, the third-party attribution file shipped in every release
# archive.
#
#   scripts/gen-notices.sh            rewrite NOTICES in place
#   scripts/gen-notices.sh --check    fail if NOTICES is out of date
#
# Two kinds of third-party code are statically linked into `entire-graph` and
# therefore have to be attributed when a binary is distributed:
#
#   1. C parser sources vendored into this repository under internal/, each
#      shipped with the upstream license file it came with.
#   2. Go modules compiled into the binary, whose license files live in the
#      module cache.
#
# Both sets are discovered, never hand-listed, so a new grammar or dependency
# cannot silently ship unattributed. A license text this script cannot classify
# is a hard error rather than an unlabeled entry.
set -eu

repo_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_root"

check_only=0
case "${1:-}" in
	--check) check_only=1 ;;
	"") ;;
	*)
		printf 'usage: %s [--check]\n' "$0" >&2
		exit 2
		;;
esac

# The platforms scripts/release.sh builds. The module set is not identical
# across them (golang.org/x/sys is reached only by the Windows builds), so the
# union of all six is what a release actually distributes.
targets='linux/amd64 linux/arm64 darwin/amd64 darwin/arm64 windows/amd64 windows/arm64'

work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT
out="$work/NOTICES"

# classify_license FILE
#
# Prints a short SPDX identifier for a license file, based on text that is
# actually present in it. Unrecognized text prints nothing and the caller
# fails, so an unreviewed license can never reach NOTICES with a guessed label.
classify_license() {
	file=$1
	if grep -q 'Apache License' "$file" && grep -q 'Version 2.0' "$file"; then
		printf 'Apache-2.0'
		return
	fi
	if grep -q 'CC0 1.0 Universal' "$file"; then
		printf 'CC0-1.0'
		return
	fi
	if grep -q 'Redistribution and use in source and binary forms' "$file"; then
		if grep -q 'Neither the name' "$file"; then
			printf 'BSD-3-Clause'
			return
		fi
		printf 'BSD-2-Clause'
		return
	fi
	# The MIT permission grant is the reliable marker: several upstreams ship
	# the MIT body with no "MIT License" heading at all.
	if grep -q 'Permission is hereby granted, free of charge' "$file" &&
		grep -q 'without restriction' "$file"; then
		printf 'MIT'
		return
	fi
}

emit_license_file() {
	label=$1
	file=$2
	spdx=$(classify_license "$file")
	if [ -z "$spdx" ]; then
		printf '%s: unrecognized license text in %s\n' "$0" "$file" >&2
		printf 'Classify it in classify_license() before releasing.\n' >&2
		exit 1
	fi
	printf -- '--------------------------------------------------------------------------------\n' >>"$out"
	printf '%s\n' "$label" >>"$out"
	printf 'License: %s (verbatim text of %s follows)\n' "$spdx" "${file##*/}" >>"$out"
	printf -- '--------------------------------------------------------------------------------\n\n' >>"$out"
	cat "$file" >>"$out"
	printf '\n' >>"$out"
}

cat >"$out" <<'HEADER'
THIRD-PARTY NOTICES
===================

This file lists third-party software statically linked into the `entire-graph`
binary distributed in this archive, together with the verbatim license text
each upstream ships. Entire Graph itself is distributed under the MIT License;
see the LICENSE file beside this one.

Generated by scripts/gen-notices.sh. Do not edit by hand.

HEADER

# ---------------------------------------------------------------------------
# 1. Vendored C parser sources.
# ---------------------------------------------------------------------------
cat >>"$out" <<'SECTION'
================================================================================
1. Vendored parser sources compiled into the binary
================================================================================

These tree-sitter grammars are vendored into the Entire Graph source tree and
compiled into the binary through cgo. Each entry names the directory the source
lives in and reproduces the license file vendored alongside it.

SECTION

# Read from a file rather than a pipe: a pipeline body runs in a subshell,
# where the fail-closed `exit 1` in emit_license_file would be swallowed.
vendored="$work/vendored"
# Test fixtures are not linked into the binary and must not be attributed as
# if they were.
# Split rather than piped into sort: in a pipeline only the last command's exit
# status reaches `set -e`, so a failing `find` would hide behind a successful
# `sort` and yield a short list that silently under-reports attribution.
find internal -type f -name LICENSE -not -path '*/testdata/*' >"$vendored"
sort -o "$vendored" "$vendored"
if [ ! -s "$vendored" ]; then
	printf '%s: found no vendored license files under internal/\n' "$0" >&2
	exit 1
fi

while IFS= read -r license_file; do
	dir=${license_file%/LICENSE}
	emit_license_file "$dir" "$license_file"
done <"$vendored"

# ---------------------------------------------------------------------------
# 2. Go module dependencies.
# ---------------------------------------------------------------------------
cat >>"$out" <<'SECTION'
================================================================================
2. Go module dependencies compiled into the binary
================================================================================

Every module below is reached by `go list -deps ./cmd/entire-graph` on at least
one of the six released platforms, and is therefore linked into at least one
released binary. Versions match go.mod at the time this file was generated.

SECTION

module_template='{{if .Module}}{{if not .Module.Main}}{{.Module.Path}}	{{.Module.Version}}	{{.Module.Dir}}{{end}}{{end}}'

modules="$work/modules"
: >"$modules"
# Cross-target listing runs without cgo because no cross C toolchain is assumed
# here. That excludes this repository's own cgo parser packages, which import
# nothing outside the standard library and so contribute no module of their
# own; `-e` keeps the walk going past them. The host pass below is the guard
# that this exclusion loses nothing.
for target in $targets; do
	GOOS=${target%/*} GOARCH=${target#*/} CGO_ENABLED=0 \
		go list -e -deps -f "$module_template" ./cmd/entire-graph >>"$modules"
done
sort -u -o "$modules" "$modules"

if [ ! -s "$modules" ]; then
	printf '%s: resolved no module dependencies\n' "$0" >&2
	exit 1
fi

# Guard: a full cgo-enabled host listing must resolve cleanly, and every module
# it reaches must already be in the union above.
host_modules="$work/host-modules"
# Not a pipeline: `set -e` reports only a pipeline's last exit status, which
# would hide a `go list` failure behind a successful `sort`.
CGO_ENABLED=1 go list -deps -f "$module_template" ./cmd/entire-graph >"$host_modules"
sort -u -o "$host_modules" "$host_modules"
while IFS= read -r host_line; do
	[ -n "$host_line" ] || continue
	if ! grep -Fqx "$host_line" "$modules"; then
		printf '%s: cgo-enabled host build reaches a module the cross listing missed:\n  %s\n' \
			"$0" "$host_line" >&2
		exit 1
	fi
done <"$host_modules"

while IFS='	' read -r mod_path mod_version mod_dir; do
	[ -n "$mod_path" ] || continue
	if [ -z "$mod_dir" ] || [ ! -d "$mod_dir" ]; then
		printf '%s: no local source for %s@%s (run `go mod download`)\n' "$0" "$mod_path" "$mod_version" >&2
		exit 1
	fi
	found=0
	# LICENSE is the grant. NOTICE is required to travel with Apache-2.0 works.
	# PATENTS is the additional grant the Go project ships beside its BSD text.
	for name in LICENSE LICENSE.txt LICENSE.md COPYING COPYING.txt NOTICE NOTICE.txt PATENTS; do
		[ -f "$mod_dir/$name" ] || continue
		found=1
		case "$name" in
			NOTICE*)
				printf -- '--------------------------------------------------------------------------------\n' >>"$out"
				printf '%s@%s\n' "$mod_path" "$mod_version" >>"$out"
				printf 'Upstream NOTICE file (reproduced as required by Apache-2.0 section 4d)\n' >>"$out"
				printf -- '--------------------------------------------------------------------------------\n\n' >>"$out"
				cat "$mod_dir/$name" >>"$out"
				printf '\n' >>"$out"
				;;
			PATENTS)
				printf -- '--------------------------------------------------------------------------------\n' >>"$out"
				printf '%s@%s\n' "$mod_path" "$mod_version" >>"$out"
				printf 'Additional patent grant (verbatim text of PATENTS follows)\n' >>"$out"
				printf -- '--------------------------------------------------------------------------------\n\n' >>"$out"
				cat "$mod_dir/$name" >>"$out"
				printf '\n' >>"$out"
				;;
			*)
				emit_license_file "$mod_path@$mod_version" "$mod_dir/$name"
				;;
		esac
	done
	if [ "$found" -eq 0 ]; then
		printf '%s: no license file found for %s@%s in %s\n' "$0" "$mod_path" "$mod_version" "$mod_dir" >&2
		exit 1
	fi
done <"$modules"

cat >>"$out" <<'FOOTER'
================================================================================
Scope note
================================================================================

github.com/smacker/go-tree-sitter bundles the tree-sitter C runtime and a
further set of grammar sources in subdirectories of the module. That module
distributes a single top-level license file covering its contents and ships no
per-grammar license file, so the module's own license text above is the whole
of what upstream provides for those sources.

FOOTER

if [ "$check_only" -eq 1 ]; then
	if [ ! -f NOTICES ]; then
		printf '%s: NOTICES is missing; run scripts/gen-notices.sh\n' "$0" >&2
		exit 1
	fi
	if ! diff -u NOTICES "$out" >&2; then
		printf '%s: NOTICES is out of date; run scripts/gen-notices.sh\n' "$0" >&2
		exit 1
	fi
	printf 'NOTICES is up to date\n' >&2
	exit 0
fi

cp "$out" NOTICES
printf 'wrote %s/NOTICES\n' "$repo_root" >&2
